---
title: "DDPWeek4"
author: "Rahul Das"
date: "09/11/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#UI side 
'''{r}
#UI File

library(shiny)


# Plot Application
shinyUI(fluidPage(
  
  # Heading
  titlePanel("United States Crime Stats, Nineteen Seventy Three"),
  
  # Bar in the side
  sidebarLayout(
    sidebarPanel(
      selectInput("place", "Select Place:",
                  unique(state.region)),
      uiOutput("SelectState"),
      p("Instructions for using this:"),
      p("This application utilizes information from the USArrests informational index in R to give a representation of 
Capture records by state for the wrongdoings of Murder, Assault and Rape in 1973. 
The client chooses the state for which he might want to see Arrest information 
by first choosing a Region and afterward a State (after choosing a district, 
the States in that Region will populate under the decision of State).
The bar statures mirror the Arrest rates per 100,000 individuals. The table in the upper 
left hand corner shows records demonstrating 
the capture pace of that state comparative with the normal of all states in the country and the 
chosen locale. 
(1 methods the Arrest Rate rises to the normal). 
The shade of the bars mirrors the locale chose.")
    ), 
    
    #
    mainPanel(
      h3(textOutput("nameofplce")),
      h3(textOutput("nameofstate")),
      plotOutput("graph")
      
      
    ))
)
)
'''
#serverside
'''{r}
#Server File
library(shiny)

shinyServer(function(input, output) {
  
  output$SelectState <- renderUI({
    selectInput("choosestate", "Choose States", state.name[state.region==input$region])
  })
  
  output$regionname <- renderText(input$region)
  
  output$statename <- reactive(input$choosestate)
  
  output$crimeplot <- renderPlot({
    
    #Loading Data
    dataframe<- USArrests[input$choosestate,]
    bhs <- c(dataframe$Murder, dataframe$Rape, dataframe$Assault)
    matplotting <- matrix(nrow=1, ncol=3, data=bhs)
    namecolumns(matplotting) <- c("Murder", "Rape", "Assault")
    
    ## Feature Calculation
    average_nationale <- c(mean(USArrests$Murder),mean(USArrests$Rape),mean(USArrests$Assault))
    stateaverage<-state.region==input$region
    crimeplace<-mean(USArrests$Murder[instates])
    balaatkaar<- mean(USArrests$Rape[instates])
    violence<- mean(USArrests$Assault[instates])
    meanofplace<-c(crimeplace, balaatkaar, violence)
    comparedtocountryavg <- round(bhs/average_nationale, digits=2)
    comparedtoplacemean <- round(bhs/meanofplace, digits=2)
    
    # Formatting
    colour<-"gray"
    if(input$region=="South"){colour<-"purple"}
    if(input$region=="West"){colour<-"coral"}
    if(input$region=="Northeast"){colour<-"light blue"}
    if(input$region=="North Central"){colour<-"hotpink"}
    
    # Plotting
    echs<-barplot(matplotting, 
               ylim=c(0,375), 
               col=regioncolor,
               main="Arrest frequency vs national avg",
               ylab="each 100k people arrest frequency")
    why<- c(dataframe$Murder, dataframe$Rape, dataframe$Assault)
    echs
    legend('topleft', ncol = 3L, title = 'vs state avg', bg="wheat",
           legend = c("Crime", "Murder" , "Rape", "Assault", "Nation",
                      comparedtocountryavg, "Region", comparedtoplacemean))
  }) 
  
})   




'''